Controllers/DrawingsController.cs
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Threading.Tasks;
using AutoMapper;
using BlackHills.Models;
using BlackHills.ViewModel;
using DigitalLibrary;
using Microsoft.AspNetCore.Hosting;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.Extensions.Logging;

namespace BlackHills.Controllers
{
    public class DrawingsController : Controller
    {

        private readonly ApplicationDbContext _DrawingsDbContext;
        private readonly IMapper _mapper;
        private readonly IWebHostEnvironment webHostEnvironment;
        private readonly ILogger<DrawingsController> _logger;

        public DrawingsController(ApplicationDbContext projectDbContext, IMapper mapper, IWebHostEnvironment hostEnvironment, ILogger<DrawingsController> logger)
        {
            _DrawingsDbContext = projectDbContext;
            _mapper = mapper;
            webHostEnvironment = hostEnvironment;
            _logger = logger;
        }

        public IActionResult Index(string status, string selection)
        {
            DrawingsListModel DLM = new DrawingsListModel();
            try
            {
                
                var DrawingsListResult = (from d in _DrawingsDbContext.Drawings
                                          join u in _DrawingsDbContext.Units
                                          on d.UnitId equals u.UnitId
                                          join f in _DrawingsDbContext.Facilities
                                          on u.FacilityId equals f.FacilityId
                                          select new DrawingsViewModel()
                                          {
                                              DrawingId = d.DrawingId,
                                              DrawingName = d.DrawingName,
                                              SystemDescription = d.SystemDescription,
                                              FilePath = d.FilePath,
                                              UnitId = d.UnitId,
                                              UnitDesc = u.UnitName,
                                              FacilityId = f.FacilityId,
                                              FacilityDesc = f.FacilityName,
                                              isActive = d.isActive,
                                              unitStatus = u.isActive
                                          }).AsQueryable();



                if (status == null)
                {
                    status = "true";
                }

                DrawingsListResult = DrawingsListResult.Where(D => D.isActive == Boolean.Parse(status));

                var DrawingResultsFiltered = DrawingsListResult.ToList();

                var vm = from i in DrawingResultsFiltered
                         select _mapper.Map<DrawingsViewModel>(i);
                DLM.Data = vm.OrderBy(d => d.FacilityDesc).ThenBy(d => d.UnitDesc).ThenBy(d => d.DrawingName).ToList();

            }
            catch (Exception ex)
            {
                if (Constants.isAdmin)
                {
                    _logger.LogError(ex.ToString());
                    return Content(Constants.GeneralExceptionAdminMessage);
                }
                else
                {
                    _logger.LogError(ex.ToString());
                    return Content(Constants.GeneralExceptionUserMessage);
                }
            }
            ViewBag.selectedOption = selection;
            ViewBag.displayStatus = status;
            return View(DLM);
        }

        public IActionResult AddDrawing(string displayStatus, string selection)
        {
             DrawingsViewModel DVM = new DrawingsViewModel();
            try
            {
                List<SelectListItem> facilitiesList = _DrawingsDbContext.Facilities.Where(F => F.isActive == true).ToList().ConvertAll(a =>
                              new SelectListItem()
                              {
                                  Text = a.FacilityName.ToString(),
                                  Value = a.FacilityId.ToString(),
                              }
                      );

                var drawingsList = (from draw in _DrawingsDbContext.Drawings
                                    select new string(draw.UnitId + ";" + draw.DrawingName))
                            .ToList();
                DVM.drawingsMasterList = drawingsList;
                DVM.ListFacilities = facilitiesList;
                List<SelectListItem> unitsList = new List<SelectListItem>();
                DVM.ListUnits = unitsList;
                DVM.isActive = true;
            }
            catch (Exception ex)
            {
                if (Constants.isAdmin)
                {
                    _logger.LogError(ex.ToString());
                    return Content(Constants.GeneralExceptionAdminMessage);
                }
                else
                {
                    _logger.LogError(ex.ToString());
                    return Content(Constants.GeneralExceptionUserMessage);
                }
            }
            ViewBag.TitleMessage = "Add Drawing";
            ViewBag.selectedOption = selection;
            ViewBag.displayStatus = displayStatus;
            return PartialView("~/Views/Drawings/_DrawingsPartial.cshtml", DVM);
        }
        public IActionResult LoadUnitsDropdown(int id)
        {
            int facId =  id;
            List<SelectListItem> unitsList = new List<SelectListItem>();

            try
            {
                if (facId != 0)
                {
                    unitsList = _DrawingsDbContext.Units.Where(u => u.FacilityId == facId && u.isActive == true).ToList().ConvertAll(a =>
                          new SelectListItem()
                          {
                              Text = a.UnitName.ToString(),
                              Value = a.UnitId.ToString(),
                          }
                    );
                }
            }
            catch (Exception ex)
            {
                if (Constants.isAdmin)
                {
                    _logger.LogError(ex.ToString());
                    return Content(Constants.GeneralExceptionAdminMessage);
                }
                else
                {
                    _logger.LogError(ex.ToString());
                    return Content(Constants.GeneralExceptionUserMessage);
                }
            }

            return Json(unitsList);
        }

        public IActionResult EditDrawing(string drawingId, string displayStatus, string selection)
        {
            DrawingsViewModel dvm = new DrawingsViewModel();
            try
            {
                var editDrawing = (from d in _DrawingsDbContext.Drawings
                                   join u in _DrawingsDbContext.Units
                                   on d.UnitId equals u.UnitId
                                   join f in _DrawingsDbContext.Facilities
                                   on u.FacilityId equals f.FacilityId
                                   where d.DrawingId == Convert.ToInt32(drawingId)
                                   select new DrawingsViewModel()
                                   {
                                       DrawingId = d.DrawingId,
                                       DrawingName = d.DrawingName,
                                       SystemDescription = d.SystemDescription,
                                       FilePath = d.FilePath,
                                       FileName = d.FileName,
                                       UnitId = d.UnitId,
                                       UnitDesc = u.UnitName,
                                       FacilityId = f.FacilityId,
                                       FacilityDesc = f.FacilityName,
                                       isActive = d.isActive
                                   }).FirstOrDefault();
                dvm.DrawingId = editDrawing.DrawingId;
                dvm.DrawingName = editDrawing.DrawingName;
                List<SelectListItem> facilitiesList = _DrawingsDbContext.Facilities.Where(F => F.isActive == true).ToList().ConvertAll(a =>
                        new SelectListItem()
                        {
                            Text = a.FacilityName.ToString(),
                            Value = a.FacilityId.ToString(),
                        }
                );
                List<SelectListItem> unitsList = _DrawingsDbContext.Units.Where(u => u.FacilityId == editDrawing.FacilityId && u.isActive == true).ToList().ConvertAll(a =>
                           new SelectListItem()
                           {
                               Text = a.UnitName.ToString(),
                               Value = a.UnitId.ToString(),
                           }
                     );
                dvm.ListFacilities = facilitiesList;
                dvm.FacilityId = editDrawing.FacilityId;
                dvm.ListUnits = unitsList;
                dvm.UnitId = editDrawing.UnitId;
                dvm.SystemDescription = editDrawing.SystemDescription;
                dvm.FilePath = editDrawing.FilePath;
                dvm.FileName = editDrawing.FileName;
                var drawingsList = (from draw in _DrawingsDbContext.Drawings
                                    where (draw.DrawingId != int.Parse(drawingId))
                                    select new string(draw.UnitId + ";" + draw.DrawingName))
                            .ToList();
                dvm.drawingsMasterList = drawingsList;
                dvm.isActive = editDrawing.isActive;
            }
            catch (Exception ex)
            {
                if (Constants.isAdmin)
                {
                    _logger.LogError(ex.ToString());
                    return Content(Constants.GeneralExceptionAdminMessage);

Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - BlackHills Page</title>
    <link rel="stylesheet" href="~/css/site.css" />
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
</head>
@using Microsoft.Extensions.Configuration
@inject IConfiguration Configuration

<body>
    <header>
        <br />
        <div class="col-11">
            <span style="float:right"><partial name="_LoginPartial" /></span>
        </div>
        <div class="row">
            <div class="col-3"></div>
            <div class="col-9">
                <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index"><h2><img src="~/images/logo.png" /> <b>Black Hills Generation Digital Library</b> </h2></a>
            </div>
        </div>
        <div>
            <div class="Col-12">
                <nav class="navbar-dark bg-dark">
                    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarToggleExternalContent" aria-controls="navbarToggleExternalContent" aria-expanded="false" aria-label="Toggle navigation">
                        <span class="navbar-toggler-icon"></span>
                    </button>

                    <label class="lable-control text-center" style="float: right;vertical-align: text-bottom;">
                        <font color="darkorange" ; size="3">For technical support, email:</font> &nbsp;&nbsp;
                        <font color="darkorange" ; size="3">BHEPowerGenerationDocumentControls@BlackhillsEnergy.com</font>
                        &nbsp;&nbsp;
                    </label>
                </nav>
            </div>

            @if (User.Claims.Where(c => c.Type == "groups").Where(v => v.Value == @Configuration.GetSection("Groups")["GroupAdmin"]).Count() != 0)
            {

                <div class="collapse" id="navbarToggleExternalContent">
                    <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom mb-3">
                        <div class="container">
                            <div class="navbar-collapse collapse d-sm-inline-flex flex-sm-row-reverse">
                                <ul class="navbar-nav flex-grow-1">
                                    <li class="nav-item">
                                        <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                                    </li>
                                    <li class="nav-item">
                                        <a class="nav-link text-dark" asp-area="" asp-controller="Facilities" asp-action="Index">Facilities</a>
                                    </li>
                                    <li class="nav-item">
                                        <a class="nav-link text-dark" asp-area="" asp-controller="Units" asp-action="Index">Units</a>
                                    </li>
                                    <li class="nav-item">
                                        <a class="nav-link text-dark" asp-area="" asp-controller="Drawings" asp-action="Index">Drawings</a>
                                    </li>
                                </ul>
                            </div>
                        </div>
                    </nav>
                </div>
            }
        </div>
        <br />
        <div class="rowBorder"></div>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    <script src="~/Scripts/jquery-1.10.2.min.js"></script>
    <link rel="stylesheet" href="//code.jquery.com/ui/1.12.1/themes/base/jquery-ui.css">
    <script src="https://code.jquery.com/ui/1.12.1/jquery-ui.js"></script>
    <link rel="stylesheet" type="text/css" href="//cdn.datatables.net/1.10.25/css/jquery.dataTables.min.css" />
    <script type="text/javascript" src="//cdn.datatables.net/1.10.25/js/jquery.dataTables.min.js"></script>
    <script>
    window.resolveUrl = function(url) {
        return "@Url.Content("~")" + url;
    };
    </script>
    @RenderSection("Scripts", required: false)
</body>
</html>